name:                emergence 
version:             0.1.0.0
github:              "MatrixAI/Emergence"
license:             Apache-2.0
author:              "CMCDragonkai"
maintainer:          "roger.qiu@matrix.ai"
copyright:           "Copyright: (c) 2017 Matrix AI"

extra-source-files:
- README.md
- package.yaml

description:         Please see the README on Github at <https://github.com/MatrixAI/Emergence#readme>

dependencies:
- base >= 4.7 && < 5
- typed-process >= 0.2.3 && < 0.3
- aeson >= 1.3.1.1 && < 1.4
- aeson-casing >= 0.1.0.5 && < 0.2
- cryptohash-sha256 >= 0.11.101 && < 0.12
- containers
- bytestring
- filepath
- directory
- crypto-multihash >= 0.4.2.0 && < 0.5
- libnix

build-tools:
- runc

library:
  source-dirs: src
  exposed-modules:
    - Lib

executables:
  emergence-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - emergence

tests:
  emergence-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - emergence
