name:                hs-libcontainer
version:             0.1.0.0
github:              "MatrixAI/hs-libcontainer"
license:             BSD3
author:              "MatrixAI"
maintainer:          ""
copyright:           "Copyright: (c) 2018 Matrix AI"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/CMCDragonkai/graphql-demo#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  c-sources:
    - src/cbits/oci-spec.c
  include-dirs: src/include
  install-includes: oci-spec.h

executables:
  hs-libcontainer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-libcontainer

tests:
  hs-libcontainer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-libcontainer
