name:                struct-ffi-prac
version:             0.1.0.0
github:              "githubuser/struct-ffi-prac"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/struct-ffi-prac#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  include-dirs: src/test
  install-includes: test.h

executables:
  struct-ffi-prac-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -dynamic
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - struct-ffi-prac
    extra-lib-dirs:
      src/test
    extra-libraries:
      test

tests:
  struct-ffi-prac-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - struct-ffi-prac
